### ISSUE TITLE
ctf_file argument in match_template.py

### ISSUE THREAD

**Issue by nadisha93** [KosinskiLab/pyTME#10]
Hello,

Really enjoying exploring this software for my particle picking. I have few questions regarding the ctf_file argument. What is the default value for ctf_file in case a ctf_file is not provided? and if the input target file is already ctf corrected, how does pytme interpret that? Does giving a ctf_file improve the quality of particle picking significantly?

On a different note, I was also wondering what other file types can be given as inputs other than the types specified? Are tiff. files compatible? Are there any examples of other file types that you have tested the software with? and lastly do you have an idea on what the maximum size of input file pytme could handle?

Thank you so much!

**Comment by maurerv** [comment]
Hi,

Very glad to hear that! 

The ctf_file allows you to specify CTF parameters for each tilt, accounting for changes through the tilt series and resulting in a CTF mask that more closely resembles the true modulation by the microscope. This is different from `--defocus`, which assumes constant defocus throughout tilts. During template matching, the template is modulated by the CTF mask, which is phase-flipped by default. Therefore, if your target has been CTF-corrected using phase-flipping, for instance like in IMOD, this option is for you. If your target has not been CTF-corrected, this should be deactivated by setting `--no_flip_phase`. In terms of quality, using the average defocus of your tilt series in `--defocus` should yield a good starting point. If the quality is utterly insufficient, it is unlikely that providing `--ctf_file` will rescue performance. In such cases, it's better to revise template generation, which will be covered in the next versions. For reference, I have used cisTEM's [simulate](https://grigoriefflab.umassmed.edu/simulate) in the past.

pyTME reads inputs using [Density.from_file](https://kosinskilab.github.io/pyTME/reference/api/tme.density.Density.from_file.html), which can also read a variety of image formats such as tiff. Currently, match_template.py is softly restricted to 3D data, but this restriction will be lifted in the next release. You can already try this unrestricted version by updating pytme: `pip install git+https://github.com/KosinskiLab/pyTME`.

There is no maximum input size because pyTME is aware of the resources required for its template matching routines and finds a match between required and available resources. However, to complete the task in a reasonable time, you should consider using GPUs for large datasets :)

**Comment by nadisha93** [comment]
Hello again!

I found out that the software picks quite a lot of particles outside of the lamellae. Do you have any suggestions on how to minimise this? One suggestion that I got is creating a mask for the tomogram, is this something possible with the preprocessor?

Thank you!

**Comment by maurerv** [comment]
Hi @nadisha93,

Using the preprocessor is definitely an option. For simple masks, here is what I typically do:

- Create a new shapes layer in the GUI
- Press "P" to create a polygon that encapsulates your region of interest
- Select the tomogram you want to mask and "Shape" in the Choose Mask tab
- Click "Create Mask" to propagate the polygon shape throughout the remaining axis

You can add additional shapes to the same layer to create more complex masks. However, they will always be symmetric along the remaining axis, and depending on the number of tomograms, this can be laborious. Alternatively, if the noise is less structured and more due to contamination, you can also:

- Choose Mask "Threshold" with a standard deviation and sigma value of 4

This will identify regions of high intensity and blur them with a Gaussian filter. These parameters should give a starting point but might need to be tuned. Finally, if you have not already, make sure to use `--mask_edges` or `--min_boundary_distance` in postprocess.py to avoid picking particles close to data borders :)

**Comment by nadisha93** [comment]
Hi @maurerv,

Thank you so much, the polygon mask worked well for me. One more question, is it possible to create a .star file without extracting subtomograms in the postprocess.py relion code?

**Comment by maurerv** [comment]
Hi,

Glad to hear that did the trick :)

Unfortunately, postprocess.py cannot do that right now, but it's something we plan on adding. In the meantime, you can convert the `--ouput_format` orientations into a star file using python like so:

```
from tme import Orientations
orientations = Orientations.from_file("orientations.tsv") # Adapt to your filename
orientations.to_file("orientations.star") # Adapt to the desired output
```

The coordinates and angles describe the orientation of the particle in the input tomogram using the Relion4 convention. All particles are assigned to the same optics group, which is characterized via some default settings. The _rlnImageName is set to _{index}.mrc and might also need to be adapted depending on the downstream workflow.

**Comment by PeterVanF** [comment]
One more question. Can pyTME directly do the 3D-CTF correction for tomograms in preprocess protocol in the future? Now, we have to do it in the novactf.

**Comment by maurerv** [comment]
Hi @PeterVanF,

In principle you could do 3D-CTF correction with what is implemented in pytme, but we have no plans to add 3D-CTF correction to the preprocess protocol at the moment

**Comment by PeterVanF** [comment]
I got it. Thank you!
