### ISSUE TITLE
Quesion about the appropriate tomograms for pyTME picking 

### ISSUE THREAD

**Issue by PeterVanF** [KosinskiLab/pyTME#11]
Hi,
I want to know whether we can use the NoisetoNoise denoised tomograms, like cryoCARE tomograms, for pytme template matching. There are different tomogram reconstruction methods such as WBP, SIRT, and SART. Which one is the best for pyTME template matching? Additionally, what binning level should we use (in Å) for particle picking? Another question is whether there is a noticeable improvement in particle picking in 3D CTF-corrected tomograms, and under what circumstances should we start using 3D corrected tomograms for particle picking, considering that 3D CTF correction requires additional time to complete? If the particles are as large as ribosomes, is 3D CTF correction still necessary? Additionally, are the principles behind particle picking with pytme similar to the software stopgap, and is there a significant difference in performance between them?

**Comment by maurerv** [comment]
Hi @PeterVanF,

You raise some excellent points. Since some depend on data quality, I cannot answer them here with certainty and you simply need to try. I hope the remaining answers help in addressing some of your points :)

> I want to know whether we can use the NoisetoNoise denoised tomograms, like cryoCARE tomograms, for pytme template matching

I pick up on this in the pytme [documentation](https://kosinskilab.github.io/pyTME/quickstart/matching/particle_picking.html#remarks-on-tomogram-preprocessing). Personally, I found denoised tomograms to be more useful for visualization than template matching. Especially when it came to angular assignment accuracy, denoised tomograms would fare worse due to the reduction in high-frequency information.

> There are different tomogram reconstruction methods such as WBP, SIRT, and SART. Which one is the best for pyTME template matching?

Generally, I opt for WBP. This is also the method used by pytme to "reconstruct" 3D filters.

> Additionally, what binning level should we use (in Å) for particle picking

That depends on the signal-to-noise ratio of your data and the particle of interest. Ribosomes, for instance, are commonly picked from 4x binned tomograms (10-13 Angstrom per voxel). However, there have been some recent papers claiming excellent template matching performance for a range of macromolecules at lower binning ([NPCs](https://www.biorxiv.org/content/10.1101/2024.04.23.590733v1), [Ribosomes, Vault, Proteasome, Microtuble ...](https://www.nature.com/articles/s41467-024-47839-8)). Personally, the lowest binning I have ever used was 2x because I needed very precise angular orientation estimates.

> Another question is whether there is a noticeable improvement in particle picking in 3D CTF-corrected tomograms, and under what circumstances should we start using 3D corrected tomograms for particle picking, considering that 3D CTF correction requires additional time to complete? If the particles are as large as ribosomes, is 3D CTF correction still necessary?

For reconstituted samples you can get away with most things, for in cell measurements you might need to adapt. From my personal experience, 3D CTF correction leads to an improvement, but its not something that makes or breaks template matching (see [here](https://www.nature.com/articles/s41592-019-0580-y) for reference). Nevertheless, I would always recommend doing a simple CTF correction on your tomograms. That indeed requires additional computations, but it makes up for the time you would spend manually curating the results. 

> Additionally, are the principles behind particle picking with pytme similar to the software stopgap, and is there a significant difference in performance between them?

Stopgap, pytom, pytme (and most other tools for template matching in cryoem) use the same cross-correlation coefficient to determine similarities. The exact formula is given [here](https://kosinskilab.github.io/pyTME/reference/template_matching/api/tme.matching_scores.flc_scoring.html#tme.matching_scores.flc_scoring). Therefore, there should not be a large difference in terms of matching accuracy (see [here](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11154592/) for a comparison between pytom and pytme). However, we did show that pytme is considerably faster than other particle picking software [here](https://www.sciencedirect.com/science/article/pii/S2352711024000074).

Best wishes,
Valentin

**Comment by PeterVanF** [comment]
Got it! Thank you, Valentin, for the detailed and instructive explanation. I’ll give it a try! 
Cheers!
Peter

**Comment by PeterVanF** [comment]
Hi Valentin,

I have a follow-up question. What’s your opinion on background correction methods, like the random-phase correction in STOPGAP? Do you think it could enhance the performance of PyTME template matching?

Best regards,
Peter

**Comment by maurerv** [comment]
Hi Peter,

The approach definitely has merit but can be a bit unpredictable at times. I show how to do a similar random-phase background correction using pytme in the docs https://kosinskilab.github.io/pyTME/quickstart/matching/particle_picking.html#parameter-comparison. 

Since the phase scrambled template has no discernible features, you might need to sample a lot of rotations to get a good background. For me, using structured templates that are clearly different from my template of interest is more predictable. However, I have not assessed the performance difference systematically yet :)

**Comment by PeterVanF** [comment]
Got it. I will give it a try! Thank you!

**Comment by maurerv** [comment]
I will close this issue due to inactivity. Feel free to re-open or start a new issue if need be :)
