### ISSUE TITLE
Version 0.2.3 score space changes

### ISSUE THREAD

**Issue by clarksadil** [KosinskiLab/pyTME#15]
Dear developers,

I've been working with pyTME for template matching in 2D and 3D, and I'm really enjoying the uniform interface and it's ability to sample n-D rotation matrices.

I saw that the new match_template.py supports 2D matching, and I've been comparing the output to version 0.2.0 API. I've noticed that when using filters, the score spaces look quite different between versions, although the correct maximum is still retained. I was wondering if this is expected behavior or if there might be something I'm missing,?

Here's my setup:

- Python version: 3.11.9
- Backend: numpyfftw
- pytme version: 0.2.3

`match_template.py -m target.h5 -i template.h5 -a 1 --lowpass 10 --highpass 50 -n 1`
(Using target and template images from your documentation)

I'd really appreciate any insights you could provide. If you need any additional information or if there are specific tests you'd like me to run, please let me know.

Best regards,
Adil

**Comment by maurerv** [comment]
Hi @clarksadil,

Thank you for reaching out, and I am glad to hear you are making use of the n-D features :)

I managed to reproduce your issue, with the left-hand side showing the output on 0.2.3 and the right-hand side showing the expected behavior (They might look slightly different for you because rotation matrices for n != 3 are subject to random uniform sampling)

![score_comparison](https://github.com/user-attachments/assets/dd574741-7acc-4dc0-a1e8-886d30f13c33)

This issue was caused by incorrect internal padding in 0.2.3. I have since fixed this issue in version 0.2.4. If you would like to continue using 0.2.3, you have to consider the following

- Create a center template with optimal shape using preprocess.py and pass `--no_centering` to match_template.py
- Use custom templates and pass the `--pad_filter` flag to match_template.py

Best,
Valentin

**Comment by clarksadil** [comment]
Hi Valentin,

Thank you for your response. As per your suggestion, I upgraded to the new version and ran some tests. I'm happy to report that this has resolved the discrepancies I was seeing in the score spaces when using filters.

I appreciate your help and your work on maintaining and improving pyTME.

Best regards,
Adil

**Comment by maurerv** [comment]
Hi @clarksadil,

Glad to hear that solved your issue :)

Thanks again for bringing this to our attention!

Best,
Valentin
