### ISSUE TITLE
Postprocessor.py PeakCaller number_of_peaks

### ISSUE THREAD

**Issue by nadisha93** [KosinskiLab/pyTME#7]
Hello,

I have been trying pyTME to pick particles from my tomograms and I have a question regarding number_of_peaks in postprocessing PeakCaller. Although the .pickle file look like there are a lot of high scoring peaks aligning with particles from the target, in postprocessing only 1000 particles are thrown out in the .tsv file rather than all the particles. I experience that even if I increase the number of number_of_peaks more than 1000, it only picks 1000. What is the reason behind this? Ideally I'd like to pick all possible particles in my target. How will this be possible?

Thank you!

**Comment by maurerv** [comment]
Hi @nadisha93 :)

Thank you for reporting your issue. Which version of pytme are you using?

**Comment by nadisha93** [comment]
Hi @maurerv!

I'm using pytme version 0.2.0.

Thank you

**Comment by maurerv** [comment]
Thanks! Unfortunately, version 0.2.0 contained a bug in postprocess.py that would overwrite the number of specified peaks. We have since fixed this error, and updating pytme to the most recent 0.2.1 version should solve your issue.

For optimal performance, you could also explore the `--n_false_positives`, `--min_distance` arguments, as well as using `--peak_caller MaximumFilter` if your peaks are close to one another :)

**Comment by nadisha93** [comment]
This is extremely useful information. Thank you so much! :)
