### ISSUE TITLE
Info about the first 3 arrays in the Metadata of pickle files

### ISSUE THREAD

**Issue by DimitriosBellos** [KosinskiLab/pyTME#9]
Dear developers,

Can you please provide a bit more info regarding the first 3 arrays in the metadata section of the pickle files
As mentioned here https://kosinskilab.github.io/pyTME/quickstart/postprocessing.html#template-matching-output
The last component of a pickle file is the metadata. While there is a namespace at it is obvious what is stored there, it is not so obvious what the first 3 arrays represent. Can you please help me with this.

Kind regards,
Dimitrios Bellos

**Comment by maurerv** [comment]
Dear Dimitrios,

Thank you for your question. Indeed, this part of the output is not extensively documented and primarily serves as a carry for postprocess.py to avoid redundant/conflicting arguments.

The three arrays correspond to the target origin, template origin, and template sampling rate along each data axis as defined in the [Density](https://kosinskilab.github.io/pyTME/reference/api/tme.density.Density.html#tme.density.Density) class. These values used to be necessary for correct coordinate system handling in `output_format=alignment`, if `--cutoff_target` and `--cutoff_template` were set in match_template.py. However, since then, our convention has changed so that only the target origin array is used by postprocess.py.

Given the limited applicability of  `--cutoff_target` and `--cutoff_template,` I have been considering removing these arguments in future versions and the corresponding elements in the metadata section of the pickle file, so that only the namespace remains.

Hope this made the meaning of the metadata section elements more clear :)

Best,
Valentin
